// If you want to undef all external lib's macros
// you should include given file only after library files

// clean up
#undef SERIALIZABLE_ACCESS

#undef EXPORT_SERIALIZABLE_ARCHIVE

#undef INSTANTIABLE_TYPE
#undef POINTER_HOLD_TYPES

#undef INSTANTIABLE_KEY
#undef INSTANTIABLE

#undef SERIALIZABLE
#undef TEMPLATE_SERIALIZABLE
#undef CONDITIONAL_SERIALIZABLE
#undef SERIALIZABLE_DECLARATION
#undef SERIALIZABLE_DEFINITION

#undef BITPACK

#undef EIGHTSER_STRING_HASH
#undef EIGHTSER_TYPE_HASH
#undef EIGHTSER_EXPRESSION_HASH

#undef EIGHTSER_ARCHIVE_TRAIT_MAX_KEY_SIZE
#undef EIGHTSER_BYTE_STREAM_RESERVE_SIZE

// possible to undef
// #undef EIGHTSER_PTRTRACK_ENABLE
// #undef EIGHTSER_FILESTREAM_ENABLE
// #undef EIGHTSER_TYPE_PORTABLE_ENABLE
// #undef EIGHTSER_ANY_SUPPORT_ENABLE
// #undef EIGHTSER_GARBAGE_CHECK_ENABLE
// #undef EIGHTSER_FULLY_ENABLE

#undef EIGHTSER_REQUIRES
